// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: rinha.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cliente struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limite          int32 `protobuf:"varint,2,opt,name=limite,proto3" json:"limite,omitempty"`
	SaldoInicial    int32 `protobuf:"varint,3,opt,name=saldo_inicial,json=saldoInicial,proto3" json:"saldo_inicial,omitempty"`
	SaldoCorrente   int32 `protobuf:"varint,4,opt,name=saldo_corrente,json=saldoCorrente,proto3" json:"saldo_corrente,omitempty"`
	UltimaTransacao int32 `protobuf:"varint,5,opt,name=ultima_transacao,json=ultimaTransacao,proto3" json:"ultima_transacao,omitempty"`
}

func (x *Cliente) Reset() {
	*x = Cliente{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rinha_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cliente) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cliente) ProtoMessage() {}

func (x *Cliente) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cliente.ProtoReflect.Descriptor instead.
func (*Cliente) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{0}
}

func (x *Cliente) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cliente) GetLimite() int32 {
	if x != nil {
		return x.Limite
	}
	return 0
}

func (x *Cliente) GetSaldoInicial() int32 {
	if x != nil {
		return x.SaldoInicial
	}
	return 0
}

func (x *Cliente) GetSaldoCorrente() int32 {
	if x != nil {
		return x.SaldoCorrente
	}
	return 0
}

func (x *Cliente) GetUltimaTransacao() int32 {
	if x != nil {
		return x.UltimaTransacao
	}
	return 0
}

type Transacao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valor       int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tipo        string `protobuf:"bytes,4,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Descricao   string `protobuf:"bytes,5,opt,name=descricao,proto3" json:"descricao,omitempty"`
	RealizadaEm string `protobuf:"bytes,6,opt,name=realizada_em,proto3" json:"realizada_em,omitempty"`
}

func (x *Transacao) Reset() {
	*x = Transacao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rinha_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transacao) ProtoMessage() {}

func (x *Transacao) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transacao.ProtoReflect.Descriptor instead.
func (*Transacao) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{1}
}

func (x *Transacao) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Transacao) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Transacao) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Transacao) GetRealizadaEm() string {
	if x != nil {
		return x.RealizadaEm
	}
	return ""
}

type AddClienteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cliente *Cliente `protobuf:"bytes,1,opt,name=cliente,proto3" json:"cliente,omitempty"`
}

func (x *AddClienteRequest) Reset() {
	*x = AddClienteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rinha_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddClienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClienteRequest) ProtoMessage() {}

func (x *AddClienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClienteRequest.ProtoReflect.Descriptor instead.
func (*AddClienteRequest) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{2}
}

func (x *AddClienteRequest) GetCliente() *Cliente {
	if x != nil {
		return x.Cliente
	}
	return nil
}

type AddClienteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddClienteResponse) Reset() {
	*x = AddClienteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rinha_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddClienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClienteResponse) ProtoMessage() {}

func (x *AddClienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClienteResponse.ProtoReflect.Descriptor instead.
func (*AddClienteResponse) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{3}
}

func (x *AddClienteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddTransacaoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClienteId int32      `protobuf:"varint,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	Transacao *Transacao `protobuf:"bytes,2,opt,name=transacao,proto3" json:"transacao,omitempty"`
}

func (x *AddTransacaoRequest) Reset() {
	*x = AddTransacaoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rinha_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTransacaoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTransacaoRequest) ProtoMessage() {}

func (x *AddTransacaoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTransacaoRequest.ProtoReflect.Descriptor instead.
func (*AddTransacaoRequest) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{4}
}

func (x *AddTransacaoRequest) GetClienteId() int32 {
	if x != nil {
		return x.ClienteId
	}
	return 0
}

func (x *AddTransacaoRequest) GetTransacao() *Transacao {
	if x != nil {
		return x.Transacao
	}
	return nil
}

type Saldo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total       int32  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	DataExtrato string `protobuf:"bytes,2,opt,name=data_extrato,proto3" json:"data_extrato,omitempty"`
	Limite      int32  `protobuf:"varint,3,opt,name=limite,proto3" json:"limite,omitempty"`
}

func (x *Saldo) Reset() {
	*x = Saldo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rinha_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Saldo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Saldo) ProtoMessage() {}

func (x *Saldo) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Saldo.ProtoReflect.Descriptor instead.
func (*Saldo) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{5}
}

func (x *Saldo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Saldo) GetDataExtrato() string {
	if x != nil {
		return x.DataExtrato
	}
	return ""
}

func (x *Saldo) GetLimite() int32 {
	if x != nil {
		return x.Limite
	}
	return 0
}

type ExtratoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClienteId int32 `protobuf:"varint,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
}

func (x *ExtratoRequest) Reset() {
	*x = ExtratoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rinha_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtratoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtratoRequest) ProtoMessage() {}

func (x *ExtratoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtratoRequest.ProtoReflect.Descriptor instead.
func (*ExtratoRequest) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{6}
}

func (x *ExtratoRequest) GetClienteId() int32 {
	if x != nil {
		return x.ClienteId
	}
	return 0
}

type Extrato struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Saldo             *Saldo       `protobuf:"bytes,1,opt,name=saldo,proto3" json:"saldo,omitempty"`
	UltimasTransacoes []*Transacao `protobuf:"bytes,2,rep,name=ultimas_transacoes,proto3" json:"ultimas_transacoes,omitempty"`
}

func (x *Extrato) Reset() {
	*x = Extrato{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rinha_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extrato) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extrato) ProtoMessage() {}

func (x *Extrato) ProtoReflect() protoreflect.Message {
	mi := &file_rinha_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extrato.ProtoReflect.Descriptor instead.
func (*Extrato) Descriptor() ([]byte, []int) {
	return file_rinha_proto_rawDescGZIP(), []int{7}
}

func (x *Extrato) GetSaldo() *Saldo {
	if x != nil {
		return x.Saldo
	}
	return nil
}

func (x *Extrato) GetUltimasTransacoes() []*Transacao {
	if x != nil {
		return x.UltimasTransacoes
	}
	return nil
}

var File_rinha_proto protoreflect.FileDescriptor

var file_rinha_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x69, 0x6e, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01,
	0x0a, 0x07, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x5f, 0x69, 0x6e, 0x69, 0x63, 0x69,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x49,
	0x6e, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x5f,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x73, 0x61, 0x6c, 0x64, 0x6f, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x29, 0x0a,
	0x10, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x61, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x61, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x77, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x70, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x12, 0x22, 0x0a,
	0x0c, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x5f, 0x65, 0x6d, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x5f, 0x65,
	0x6d, 0x22, 0x37, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x65, 0x52, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x41, 0x64,
	0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x5e, 0x0a, 0x13, 0x41, 0x64,
	0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x28, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x52,
	0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x59, 0x0a, 0x05, 0x53, 0x61,
	0x6c, 0x64, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x65, 0x22, 0x2f, 0x0a, 0x0e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x65, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x07, 0x45, 0x78, 0x74, 0x72, 0x61, 0x74,
	0x6f, 0x12, 0x1c, 0x0a, 0x05, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x06, 0x2e, 0x53, 0x61, 0x6c, 0x64, 0x6f, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x12,
	0x3a, 0x0a, 0x12, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x61, 0x73, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x6f, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x12, 0x75, 0x6c, 0x74, 0x69, 0x6d, 0x61, 0x73,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x6f, 0x65, 0x73, 0x32, 0x8d, 0x01, 0x0a, 0x07,
	0x52, 0x69, 0x6e, 0x68, 0x61, 0x44, 0x42, 0x12, 0x2b, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x08, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x1a,
	0x13, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x61, 0x6f, 0x12, 0x14, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x53, 0x61, 0x6c,
	0x64, 0x6f, 0x12, 0x27, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x45, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f,
	0x12, 0x0f, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x08, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rinha_proto_rawDescOnce sync.Once
	file_rinha_proto_rawDescData = file_rinha_proto_rawDesc
)

func file_rinha_proto_rawDescGZIP() []byte {
	file_rinha_proto_rawDescOnce.Do(func() {
		file_rinha_proto_rawDescData = protoimpl.X.CompressGZIP(file_rinha_proto_rawDescData)
	})
	return file_rinha_proto_rawDescData
}

var file_rinha_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rinha_proto_goTypes = []interface{}{
	(*Cliente)(nil),             // 0: Cliente
	(*Transacao)(nil),           // 1: Transacao
	(*AddClienteRequest)(nil),   // 2: AddClienteRequest
	(*AddClienteResponse)(nil),  // 3: AddClienteResponse
	(*AddTransacaoRequest)(nil), // 4: AddTransacaoRequest
	(*Saldo)(nil),               // 5: Saldo
	(*ExtratoRequest)(nil),      // 6: ExtratoRequest
	(*Extrato)(nil),             // 7: Extrato
}
var file_rinha_proto_depIdxs = []int32{
	0, // 0: AddClienteRequest.cliente:type_name -> Cliente
	1, // 1: AddTransacaoRequest.transacao:type_name -> Transacao
	5, // 2: Extrato.saldo:type_name -> Saldo
	1, // 3: Extrato.ultimas_transacoes:type_name -> Transacao
	0, // 4: RinhaDB.AddCliente:input_type -> Cliente
	4, // 5: RinhaDB.AddTransacao:input_type -> AddTransacaoRequest
	6, // 6: RinhaDB.GetExtrato:input_type -> ExtratoRequest
	3, // 7: RinhaDB.AddCliente:output_type -> AddClienteResponse
	5, // 8: RinhaDB.AddTransacao:output_type -> Saldo
	7, // 9: RinhaDB.GetExtrato:output_type -> Extrato
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rinha_proto_init() }
func file_rinha_proto_init() {
	if File_rinha_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rinha_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cliente); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rinha_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transacao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rinha_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddClienteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rinha_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddClienteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rinha_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTransacaoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rinha_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Saldo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rinha_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtratoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rinha_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Extrato); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rinha_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rinha_proto_goTypes,
		DependencyIndexes: file_rinha_proto_depIdxs,
		MessageInfos:      file_rinha_proto_msgTypes,
	}.Build()
	File_rinha_proto = out.File
	file_rinha_proto_rawDesc = nil
	file_rinha_proto_goTypes = nil
	file_rinha_proto_depIdxs = nil
}
